export const allowedRolesMap: Record<string, string[]> = {
  // Premium ve admin erişimi
  '/users': ['admin'],
  '/kimlik-arsivi': ['admin', 'premium'],
  '/kimlik-olusturucu': ['admin', 'premium'],
  '/bin-sorgu': ['admin', 'premium'],
  '/gsm-sorgu': ['admin', 'premium'],
  '/sulale-sorgu': ['admin', 'premium'],
  '/adsoyad-sorgu': ['admin', 'premium'],
  '/kisi-bul': ['admin', 'premium'],
  '/kisi-sorgu': ['admin', 'premium'],
  '/yabanci-sorgu': ['admin', 'premium'],
  '/wexai': ['admin', 'premium'],
  '/sms-bomber': ['admin', 'premium'],
  '/panel': ['admin', 'premium'],
  '/iptv': ['admin', 'premium', 'user'],
  '/fiyat-listesi': ['admin', 'premium', 'user'],
  '/dns-domain-sorgu': ['admin', 'premium', 'user'],
  '/operator-sorgu': ['admin', 'premium', 'user'],
  '/altyapi-sorgu': ['admin', 'premium', 'user'],
  '/azerbeycan-kimlik': ['admin', 'premium', 'user'],
  '/apps': ['admin', 'premium', 'user'],
  '/chats': ['admin', 'premium', 'user'],
  '/settings': ['admin', 'premium', 'user'],
  '/help-center': ['admin', 'premium', 'user'],
} 