/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleCallbackRouteImport } from './routes/google-callback'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AuthenticatedYabanciSorguIndexRouteImport } from './routes/_authenticated/yabanci-sorgu/index'
import { Route as AuthenticatedWexaiIndexRouteImport } from './routes/_authenticated/wexai/index'
import { Route as AuthenticatedSulaleSorguIndexRouteImport } from './routes/_authenticated/sulale-sorgu/index'
import { Route as AuthenticatedSmsBomberIndexRouteImport } from './routes/_authenticated/sms-bomber/index'
import { Route as AuthenticatedOperatorSorguIndexRouteImport } from './routes/_authenticated/operator-sorgu/index'
import { Route as AuthenticatedKisiSorguIndexRouteImport } from './routes/_authenticated/kisi-sorgu/index'
import { Route as AuthenticatedKisiBulIndexRouteImport } from './routes/_authenticated/kisi-bul/index'
import { Route as AuthenticatedKimlikOlusturucuIndexRouteImport } from './routes/_authenticated/kimlik-olusturucu/index'
import { Route as AuthenticatedKimlikArsiviIndexRouteImport } from './routes/_authenticated/kimlik-arsivi/index'
import { Route as AuthenticatedIptvIndexRouteImport } from './routes/_authenticated/iptv/index'
import { Route as AuthenticatedGsmSorguIndexRouteImport } from './routes/_authenticated/gsm-sorgu/index'
import { Route as AuthenticatedFiyatListesiIndexRouteImport } from './routes/_authenticated/fiyat-listesi/index'
import { Route as AuthenticatedDnsDomainSorguIndexRouteImport } from './routes/_authenticated/dns-domain-sorgu/index'
import { Route as AuthenticatedBinSorguIndexRouteImport } from './routes/_authenticated/bin-sorgu/index'
import { Route as AuthenticatedAzerbeycanKimlikIndexRouteImport } from './routes/_authenticated/azerbeycan-kimlik/index'
import { Route as AuthenticatedAltyapiSorguIndexRouteImport } from './routes/_authenticated/altyapi-sorgu/index'
import { Route as AuthenticatedAdsoyadSorguIndexRouteImport } from './routes/_authenticated/adsoyad-sorgu/index'

const errors503LazyRouteImport = createFileRoute('/(errors)/503')()
const errors500LazyRouteImport = createFileRoute('/(errors)/500')()
const errors404LazyRouteImport = createFileRoute('/(errors)/404')()
const errors403LazyRouteImport = createFileRoute('/(errors)/403')()
const errors401LazyRouteImport = createFileRoute('/(errors)/401')()
const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyRouteImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyRouteImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedUsersIndexLazyRouteImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedSettingsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedHelpCenterIndexLazyRouteImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedChatsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedAppsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/apps/',
)()
const AuthenticatedSettingsNotificationsLazyRouteImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyRouteImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyRouteImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyRouteImport = createFileRoute(
  '/_authenticated/settings/account',
)()

const GoogleCallbackRoute = GoogleCallbackRouteImport.update({
  id: '/google-callback',
  path: '/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503LazyRoute = errors503LazyRouteImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))
const errors500LazyRoute = errors500LazyRouteImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))
const errors404LazyRoute = errors404LazyRouteImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))
const errors403LazyRoute = errors403LazyRouteImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))
const errors401LazyRoute = errors401LazyRouteImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authSignIn2LazyRoute = authSignIn2LazyRouteImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )
const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )
const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )
const AuthenticatedAppsIndexLazyRoute =
  AuthenticatedAppsIndexLazyRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/apps/index.lazy').then((d) => d.Route),
  )
const AuthenticatedYabanciSorguIndexRoute =
  AuthenticatedYabanciSorguIndexRouteImport.update({
    id: '/yabanci-sorgu/',
    path: '/yabanci-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWexaiIndexRoute = AuthenticatedWexaiIndexRouteImport.update({
  id: '/wexai/',
  path: '/wexai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSulaleSorguIndexRoute =
  AuthenticatedSulaleSorguIndexRouteImport.update({
    id: '/sulale-sorgu/',
    path: '/sulale-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSmsBomberIndexRoute =
  AuthenticatedSmsBomberIndexRouteImport.update({
    id: '/sms-bomber/',
    path: '/sms-bomber/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorSorguIndexRoute =
  AuthenticatedOperatorSorguIndexRouteImport.update({
    id: '/operator-sorgu/',
    path: '/operator-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKisiSorguIndexRoute =
  AuthenticatedKisiSorguIndexRouteImport.update({
    id: '/kisi-sorgu/',
    path: '/kisi-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKisiBulIndexRoute =
  AuthenticatedKisiBulIndexRouteImport.update({
    id: '/kisi-bul/',
    path: '/kisi-bul/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKimlikOlusturucuIndexRoute =
  AuthenticatedKimlikOlusturucuIndexRouteImport.update({
    id: '/kimlik-olusturucu/',
    path: '/kimlik-olusturucu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKimlikArsiviIndexRoute =
  AuthenticatedKimlikArsiviIndexRouteImport.update({
    id: '/kimlik-arsivi/',
    path: '/kimlik-arsivi/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIptvIndexRoute = AuthenticatedIptvIndexRouteImport.update({
  id: '/iptv/',
  path: '/iptv/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGsmSorguIndexRoute =
  AuthenticatedGsmSorguIndexRouteImport.update({
    id: '/gsm-sorgu/',
    path: '/gsm-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFiyatListesiIndexRoute =
  AuthenticatedFiyatListesiIndexRouteImport.update({
    id: '/fiyat-listesi/',
    path: '/fiyat-listesi/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDnsDomainSorguIndexRoute =
  AuthenticatedDnsDomainSorguIndexRouteImport.update({
    id: '/dns-domain-sorgu/',
    path: '/dns-domain-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBinSorguIndexRoute =
  AuthenticatedBinSorguIndexRouteImport.update({
    id: '/bin-sorgu/',
    path: '/bin-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAzerbeycanKimlikIndexRoute =
  AuthenticatedAzerbeycanKimlikIndexRouteImport.update({
    id: '/azerbeycan-kimlik/',
    path: '/azerbeycan-kimlik/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAltyapiSorguIndexRoute =
  AuthenticatedAltyapiSorguIndexRouteImport.update({
    id: '/altyapi-sorgu/',
    path: '/altyapi-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdsoyadSorguIndexRoute =
  AuthenticatedAdsoyadSorguIndexRouteImport.update({
    id: '/adsoyad-sorgu/',
    path: '/adsoyad-sorgu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/google-callback': typeof GoogleCallbackRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/adsoyad-sorgu': typeof AuthenticatedAdsoyadSorguIndexRoute
  '/altyapi-sorgu': typeof AuthenticatedAltyapiSorguIndexRoute
  '/azerbeycan-kimlik': typeof AuthenticatedAzerbeycanKimlikIndexRoute
  '/bin-sorgu': typeof AuthenticatedBinSorguIndexRoute
  '/dns-domain-sorgu': typeof AuthenticatedDnsDomainSorguIndexRoute
  '/fiyat-listesi': typeof AuthenticatedFiyatListesiIndexRoute
  '/gsm-sorgu': typeof AuthenticatedGsmSorguIndexRoute
  '/iptv': typeof AuthenticatedIptvIndexRoute
  '/kimlik-arsivi': typeof AuthenticatedKimlikArsiviIndexRoute
  '/kimlik-olusturucu': typeof AuthenticatedKimlikOlusturucuIndexRoute
  '/kisi-bul': typeof AuthenticatedKisiBulIndexRoute
  '/kisi-sorgu': typeof AuthenticatedKisiSorguIndexRoute
  '/operator-sorgu': typeof AuthenticatedOperatorSorguIndexRoute
  '/sms-bomber': typeof AuthenticatedSmsBomberIndexRoute
  '/sulale-sorgu': typeof AuthenticatedSulaleSorguIndexRoute
  '/wexai': typeof AuthenticatedWexaiIndexRoute
  '/yabanci-sorgu': typeof AuthenticatedYabanciSorguIndexRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/google-callback': typeof GoogleCallbackRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/adsoyad-sorgu': typeof AuthenticatedAdsoyadSorguIndexRoute
  '/altyapi-sorgu': typeof AuthenticatedAltyapiSorguIndexRoute
  '/azerbeycan-kimlik': typeof AuthenticatedAzerbeycanKimlikIndexRoute
  '/bin-sorgu': typeof AuthenticatedBinSorguIndexRoute
  '/dns-domain-sorgu': typeof AuthenticatedDnsDomainSorguIndexRoute
  '/fiyat-listesi': typeof AuthenticatedFiyatListesiIndexRoute
  '/gsm-sorgu': typeof AuthenticatedGsmSorguIndexRoute
  '/iptv': typeof AuthenticatedIptvIndexRoute
  '/kimlik-arsivi': typeof AuthenticatedKimlikArsiviIndexRoute
  '/kimlik-olusturucu': typeof AuthenticatedKimlikOlusturucuIndexRoute
  '/kisi-bul': typeof AuthenticatedKisiBulIndexRoute
  '/kisi-sorgu': typeof AuthenticatedKisiSorguIndexRoute
  '/operator-sorgu': typeof AuthenticatedOperatorSorguIndexRoute
  '/sms-bomber': typeof AuthenticatedSmsBomberIndexRoute
  '/sulale-sorgu': typeof AuthenticatedSulaleSorguIndexRoute
  '/wexai': typeof AuthenticatedWexaiIndexRoute
  '/yabanci-sorgu': typeof AuthenticatedYabanciSorguIndexRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/google-callback': typeof GoogleCallbackRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/adsoyad-sorgu/': typeof AuthenticatedAdsoyadSorguIndexRoute
  '/_authenticated/altyapi-sorgu/': typeof AuthenticatedAltyapiSorguIndexRoute
  '/_authenticated/azerbeycan-kimlik/': typeof AuthenticatedAzerbeycanKimlikIndexRoute
  '/_authenticated/bin-sorgu/': typeof AuthenticatedBinSorguIndexRoute
  '/_authenticated/dns-domain-sorgu/': typeof AuthenticatedDnsDomainSorguIndexRoute
  '/_authenticated/fiyat-listesi/': typeof AuthenticatedFiyatListesiIndexRoute
  '/_authenticated/gsm-sorgu/': typeof AuthenticatedGsmSorguIndexRoute
  '/_authenticated/iptv/': typeof AuthenticatedIptvIndexRoute
  '/_authenticated/kimlik-arsivi/': typeof AuthenticatedKimlikArsiviIndexRoute
  '/_authenticated/kimlik-olusturucu/': typeof AuthenticatedKimlikOlusturucuIndexRoute
  '/_authenticated/kisi-bul/': typeof AuthenticatedKisiBulIndexRoute
  '/_authenticated/kisi-sorgu/': typeof AuthenticatedKisiSorguIndexRoute
  '/_authenticated/operator-sorgu/': typeof AuthenticatedOperatorSorguIndexRoute
  '/_authenticated/sms-bomber/': typeof AuthenticatedSmsBomberIndexRoute
  '/_authenticated/sulale-sorgu/': typeof AuthenticatedSulaleSorguIndexRoute
  '/_authenticated/wexai/': typeof AuthenticatedWexaiIndexRoute
  '/_authenticated/yabanci-sorgu/': typeof AuthenticatedYabanciSorguIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/google-callback'
    | '/otp'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/adsoyad-sorgu'
    | '/altyapi-sorgu'
    | '/azerbeycan-kimlik'
    | '/bin-sorgu'
    | '/dns-domain-sorgu'
    | '/fiyat-listesi'
    | '/gsm-sorgu'
    | '/iptv'
    | '/kimlik-arsivi'
    | '/kimlik-olusturucu'
    | '/kisi-bul'
    | '/kisi-sorgu'
    | '/operator-sorgu'
    | '/sms-bomber'
    | '/sulale-sorgu'
    | '/wexai'
    | '/yabanci-sorgu'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/google-callback'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/adsoyad-sorgu'
    | '/altyapi-sorgu'
    | '/azerbeycan-kimlik'
    | '/bin-sorgu'
    | '/dns-domain-sorgu'
    | '/fiyat-listesi'
    | '/gsm-sorgu'
    | '/iptv'
    | '/kimlik-arsivi'
    | '/kimlik-olusturucu'
    | '/kisi-bul'
    | '/kisi-sorgu'
    | '/operator-sorgu'
    | '/sms-bomber'
    | '/sulale-sorgu'
    | '/wexai'
    | '/yabanci-sorgu'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/google-callback'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/adsoyad-sorgu/'
    | '/_authenticated/altyapi-sorgu/'
    | '/_authenticated/azerbeycan-kimlik/'
    | '/_authenticated/bin-sorgu/'
    | '/_authenticated/dns-domain-sorgu/'
    | '/_authenticated/fiyat-listesi/'
    | '/_authenticated/gsm-sorgu/'
    | '/_authenticated/iptv/'
    | '/_authenticated/kimlik-arsivi/'
    | '/_authenticated/kimlik-olusturucu/'
    | '/_authenticated/kisi-bul/'
    | '/_authenticated/kisi-sorgu/'
    | '/_authenticated/operator-sorgu/'
    | '/_authenticated/sms-bomber/'
    | '/_authenticated/sulale-sorgu/'
    | '/_authenticated/wexai/'
    | '/_authenticated/yabanci-sorgu/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GoogleCallbackRoute: typeof GoogleCallbackRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-callback': {
      id: '/google-callback'
      path: '/google-callback'
      fullPath: '/google-callback'
      preLoaderRoute: typeof GoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yabanci-sorgu/': {
      id: '/_authenticated/yabanci-sorgu/'
      path: '/yabanci-sorgu'
      fullPath: '/yabanci-sorgu'
      preLoaderRoute: typeof AuthenticatedYabanciSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wexai/': {
      id: '/_authenticated/wexai/'
      path: '/wexai'
      fullPath: '/wexai'
      preLoaderRoute: typeof AuthenticatedWexaiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sulale-sorgu/': {
      id: '/_authenticated/sulale-sorgu/'
      path: '/sulale-sorgu'
      fullPath: '/sulale-sorgu'
      preLoaderRoute: typeof AuthenticatedSulaleSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms-bomber/': {
      id: '/_authenticated/sms-bomber/'
      path: '/sms-bomber'
      fullPath: '/sms-bomber'
      preLoaderRoute: typeof AuthenticatedSmsBomberIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator-sorgu/': {
      id: '/_authenticated/operator-sorgu/'
      path: '/operator-sorgu'
      fullPath: '/operator-sorgu'
      preLoaderRoute: typeof AuthenticatedOperatorSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kisi-sorgu/': {
      id: '/_authenticated/kisi-sorgu/'
      path: '/kisi-sorgu'
      fullPath: '/kisi-sorgu'
      preLoaderRoute: typeof AuthenticatedKisiSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kisi-bul/': {
      id: '/_authenticated/kisi-bul/'
      path: '/kisi-bul'
      fullPath: '/kisi-bul'
      preLoaderRoute: typeof AuthenticatedKisiBulIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kimlik-olusturucu/': {
      id: '/_authenticated/kimlik-olusturucu/'
      path: '/kimlik-olusturucu'
      fullPath: '/kimlik-olusturucu'
      preLoaderRoute: typeof AuthenticatedKimlikOlusturucuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kimlik-arsivi/': {
      id: '/_authenticated/kimlik-arsivi/'
      path: '/kimlik-arsivi'
      fullPath: '/kimlik-arsivi'
      preLoaderRoute: typeof AuthenticatedKimlikArsiviIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iptv/': {
      id: '/_authenticated/iptv/'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof AuthenticatedIptvIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gsm-sorgu/': {
      id: '/_authenticated/gsm-sorgu/'
      path: '/gsm-sorgu'
      fullPath: '/gsm-sorgu'
      preLoaderRoute: typeof AuthenticatedGsmSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiyat-listesi/': {
      id: '/_authenticated/fiyat-listesi/'
      path: '/fiyat-listesi'
      fullPath: '/fiyat-listesi'
      preLoaderRoute: typeof AuthenticatedFiyatListesiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dns-domain-sorgu/': {
      id: '/_authenticated/dns-domain-sorgu/'
      path: '/dns-domain-sorgu'
      fullPath: '/dns-domain-sorgu'
      preLoaderRoute: typeof AuthenticatedDnsDomainSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bin-sorgu/': {
      id: '/_authenticated/bin-sorgu/'
      path: '/bin-sorgu'
      fullPath: '/bin-sorgu'
      preLoaderRoute: typeof AuthenticatedBinSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/azerbeycan-kimlik/': {
      id: '/_authenticated/azerbeycan-kimlik/'
      path: '/azerbeycan-kimlik'
      fullPath: '/azerbeycan-kimlik'
      preLoaderRoute: typeof AuthenticatedAzerbeycanKimlikIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/altyapi-sorgu/': {
      id: '/_authenticated/altyapi-sorgu/'
      path: '/altyapi-sorgu'
      fullPath: '/altyapi-sorgu'
      preLoaderRoute: typeof AuthenticatedAltyapiSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adsoyad-sorgu/': {
      id: '/_authenticated/adsoyad-sorgu/'
      path: '/adsoyad-sorgu'
      fullPath: '/adsoyad-sorgu'
      preLoaderRoute: typeof AuthenticatedAdsoyadSorguIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyRoute
    }
  }
}

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdsoyadSorguIndexRoute: typeof AuthenticatedAdsoyadSorguIndexRoute
  AuthenticatedAltyapiSorguIndexRoute: typeof AuthenticatedAltyapiSorguIndexRoute
  AuthenticatedAzerbeycanKimlikIndexRoute: typeof AuthenticatedAzerbeycanKimlikIndexRoute
  AuthenticatedBinSorguIndexRoute: typeof AuthenticatedBinSorguIndexRoute
  AuthenticatedDnsDomainSorguIndexRoute: typeof AuthenticatedDnsDomainSorguIndexRoute
  AuthenticatedFiyatListesiIndexRoute: typeof AuthenticatedFiyatListesiIndexRoute
  AuthenticatedGsmSorguIndexRoute: typeof AuthenticatedGsmSorguIndexRoute
  AuthenticatedIptvIndexRoute: typeof AuthenticatedIptvIndexRoute
  AuthenticatedKimlikArsiviIndexRoute: typeof AuthenticatedKimlikArsiviIndexRoute
  AuthenticatedKimlikOlusturucuIndexRoute: typeof AuthenticatedKimlikOlusturucuIndexRoute
  AuthenticatedKisiBulIndexRoute: typeof AuthenticatedKisiBulIndexRoute
  AuthenticatedKisiSorguIndexRoute: typeof AuthenticatedKisiSorguIndexRoute
  AuthenticatedOperatorSorguIndexRoute: typeof AuthenticatedOperatorSorguIndexRoute
  AuthenticatedSmsBomberIndexRoute: typeof AuthenticatedSmsBomberIndexRoute
  AuthenticatedSulaleSorguIndexRoute: typeof AuthenticatedSulaleSorguIndexRoute
  AuthenticatedWexaiIndexRoute: typeof AuthenticatedWexaiIndexRoute
  AuthenticatedYabanciSorguIndexRoute: typeof AuthenticatedYabanciSorguIndexRoute
  AuthenticatedAppsIndexLazyRoute: typeof AuthenticatedAppsIndexLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdsoyadSorguIndexRoute: AuthenticatedAdsoyadSorguIndexRoute,
  AuthenticatedAltyapiSorguIndexRoute: AuthenticatedAltyapiSorguIndexRoute,
  AuthenticatedAzerbeycanKimlikIndexRoute:
    AuthenticatedAzerbeycanKimlikIndexRoute,
  AuthenticatedBinSorguIndexRoute: AuthenticatedBinSorguIndexRoute,
  AuthenticatedDnsDomainSorguIndexRoute: AuthenticatedDnsDomainSorguIndexRoute,
  AuthenticatedFiyatListesiIndexRoute: AuthenticatedFiyatListesiIndexRoute,
  AuthenticatedGsmSorguIndexRoute: AuthenticatedGsmSorguIndexRoute,
  AuthenticatedIptvIndexRoute: AuthenticatedIptvIndexRoute,
  AuthenticatedKimlikArsiviIndexRoute: AuthenticatedKimlikArsiviIndexRoute,
  AuthenticatedKimlikOlusturucuIndexRoute:
    AuthenticatedKimlikOlusturucuIndexRoute,
  AuthenticatedKisiBulIndexRoute: AuthenticatedKisiBulIndexRoute,
  AuthenticatedKisiSorguIndexRoute: AuthenticatedKisiSorguIndexRoute,
  AuthenticatedOperatorSorguIndexRoute: AuthenticatedOperatorSorguIndexRoute,
  AuthenticatedSmsBomberIndexRoute: AuthenticatedSmsBomberIndexRoute,
  AuthenticatedSulaleSorguIndexRoute: AuthenticatedSulaleSorguIndexRoute,
  AuthenticatedWexaiIndexRoute: AuthenticatedWexaiIndexRoute,
  AuthenticatedYabanciSorguIndexRoute: AuthenticatedYabanciSorguIndexRoute,
  AuthenticatedAppsIndexLazyRoute: AuthenticatedAppsIndexLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GoogleCallbackRoute: GoogleCallbackRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
